// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "djinni_support.hpp"
#include "people.hpp"

namespace djinni_generated {

class NativePeople final {
public:
    using CppType = ::lego::People;
    using JniType = jobject;

    using Boxed = NativePeople;

    ~NativePeople();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativePeople();
    friend ::djinni::JniClass<NativePeople>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/lego/People") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mFirstName { ::djinni::jniGetFieldID(clazz.get(), "mFirstName", "Ljava/lang/String;") };
    const jfieldID field_mLastName { ::djinni::jniGetFieldID(clazz.get(), "mLastName", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
