// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "NativePeople.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativePeople::NativePeople() = default;

NativePeople::~NativePeople() = default;

auto NativePeople::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativePeople>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.first_name)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.last_name)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativePeople::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativePeople>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mFirstName)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mLastName))};
}

}  // namespace djinni_generated
