// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "djinni_support.hpp"
#include "network_callback.hpp"

namespace djinni_generated {

class NativeNetworkCallback final : ::djinni::JniInterface<::lego::NetworkCallback, NativeNetworkCallback> {
public:
    using CppType = std::shared_ptr<::lego::NetworkCallback>;
    using CppOptType = std::shared_ptr<::lego::NetworkCallback>;
    using JniType = jobject;

    using Boxed = NativeNetworkCallback;

    ~NativeNetworkCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeNetworkCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeNetworkCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeNetworkCallback();
    friend ::djinni::JniClass<NativeNetworkCallback>;
    friend ::djinni::JniInterface<::lego::NetworkCallback, NativeNetworkCallback>;

};

}  // namespace djinni_generated
