// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "NativeTemplate.hpp"  // my header
#include "Marshal.hpp"
#include "NativePage.hpp"

namespace djinni_generated {

NativeTemplate::NativeTemplate() = default;

NativeTemplate::~NativeTemplate() = default;

auto NativeTemplate::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeTemplate>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.id)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::NativePage>::fromCpp(jniEnv, c.pages)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeTemplate::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeTemplate>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mId)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName)),
            ::djinni::List<::djinni_generated::NativePage>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mPages))};
}

}  // namespace djinni_generated
