// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "NativeAppObserver.hpp"  // my header

namespace djinni_generated {

NativeAppObserver::NativeAppObserver() : ::djinni::JniInterface<::lego::AppObserver, NativeAppObserver>() {}

NativeAppObserver::~NativeAppObserver() = default;

NativeAppObserver::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeAppObserver::JavaProxy::~JavaProxy() = default;


}  // namespace djinni_generated
