// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "djinni_support.hpp"
#include "page.hpp"

namespace djinni_generated {

class NativePage final {
public:
    using CppType = ::lego::Page;
    using JniType = jobject;

    using Boxed = NativePage;

    ~NativePage();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativePage();
    friend ::djinni::JniClass<NativePage>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/lego/Page") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;ILjava/util/ArrayList;)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/String;") };
    const jfieldID field_mTitle { ::djinni::jniGetFieldID(clazz.get(), "mTitle", "Ljava/lang/String;") };
    const jfieldID field_mOrder { ::djinni::jniGetFieldID(clazz.get(), "mOrder", "I") };
    const jfieldID field_mQuestions { ::djinni::jniGetFieldID(clazz.get(), "mQuestions", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
