// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "NativeUiObserver.hpp"  // my header
#include "Marshal.hpp"
#include "NativePeople.hpp"

namespace djinni_generated {

NativeUiObserver::NativeUiObserver() : ::djinni::JniInterface<::lego::UiObserver, NativeUiObserver>() {}

NativeUiObserver::~NativeUiObserver() = default;

NativeUiObserver::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeUiObserver::JavaProxy::~JavaProxy() = default;

void NativeUiObserver::JavaProxy::title_updated(const std::string & c_title) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeUiObserver>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_titleUpdated,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_title)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeUiObserver::JavaProxy::people_updated(const ::lego::People & c_people) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeUiObserver>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_peopleUpdated,
                           ::djinni::get(::djinni_generated::NativePeople::fromCpp(jniEnv, c_people)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
