// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "djinni_support.hpp"
#include "task.hpp"

namespace djinni_generated {

class NativeTask final : ::djinni::JniInterface<::lego::Task, NativeTask> {
public:
    using CppType = std::shared_ptr<::lego::Task>;
    using CppOptType = std::shared_ptr<::lego::Task>;
    using JniType = jobject;

    using Boxed = NativeTask;

    ~NativeTask();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTask>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTask>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTask();
    friend ::djinni::JniClass<NativeTask>;
    friend ::djinni::JniInterface<::lego::Task, NativeTask>;

};

}  // namespace djinni_generated
