// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "NativeAppManager.hpp"  // my header
#include "Marshal.hpp"
#include "NativeAppObserver.hpp"

namespace djinni_generated {

NativeAppManager::NativeAppManager() : ::djinni::JniInterface<::lego::AppManager, NativeAppManager>("com/mycompany/lego/AppManager$CppProxy") {}

NativeAppManager::~NativeAppManager() = default;


CJNIEXPORT void JNICALL Java_com_mycompany_lego_AppManager_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::lego::AppManager>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_lego_AppManager_create(JNIEnv* jniEnv, jobject /*this*/, jobject j_observer)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::lego::AppManager::create(::djinni_generated::NativeAppObserver::toCpp(jniEnv, j_observer));
        return ::djinni::release(::djinni_generated::NativeAppManager::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_mycompany_lego_AppManager_00024CppProxy_native_1updateTimeString(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_timeString)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::lego::AppManager>(nativeRef);
        ref->update_time_string(::djinni::String::toCpp(jniEnv, j_timeString));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
