// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "NativeSQuestion.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSQuestion::NativeSQuestion() = default;

NativeSQuestion::~NativeSQuestion() = default;

auto NativeSQuestion::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSQuestion>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.id)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.title)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.response_type)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.question_description)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.order)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSQuestion::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSQuestion>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mId)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mTitle)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mResponseType)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mQuestionDescription)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mOrder))};
}

}  // namespace djinni_generated
