// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "NativePage.hpp"  // my header
#include "Marshal.hpp"
#include "NativeQuestion.hpp"

namespace djinni_generated {

NativePage::NativePage() = default;

NativePage::~NativePage() = default;

auto NativePage::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativePage>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.id)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.title)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.order)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::NativeQuestion>::fromCpp(jniEnv, c.questions)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativePage::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativePage>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mId)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mTitle)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mOrder)),
            ::djinni::List<::djinni_generated::NativeQuestion>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mQuestions))};
}

}  // namespace djinni_generated
