// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "djinni_support.hpp"
#include "template.hpp"

namespace djinni_generated {

class NativeTemplate final {
public:
    using CppType = ::lego::Template;
    using JniType = jobject;

    using Boxed = NativeTemplate;

    ~NativeTemplate();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeTemplate();
    friend ::djinni::JniClass<NativeTemplate>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/lego/Template") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/String;") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
    const jfieldID field_mPages { ::djinni::jniGetFieldID(clazz.get(), "mPages", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
