// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "djinni_support.hpp"
#include "ui_platform_support.hpp"

namespace djinni_generated {

class NativeUiPlatformSupport final : ::djinni::JniInterface<::lego::UiPlatformSupport, NativeUiPlatformSupport> {
public:
    using CppType = std::shared_ptr<::lego::UiPlatformSupport>;
    using CppOptType = std::shared_ptr<::lego::UiPlatformSupport>;
    using JniType = jobject;

    using Boxed = NativeUiPlatformSupport;

    ~NativeUiPlatformSupport();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeUiPlatformSupport>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeUiPlatformSupport>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeUiPlatformSupport();
    friend ::djinni::JniClass<NativeUiPlatformSupport>;
    friend ::djinni::JniInterface<::lego::UiPlatformSupport, NativeUiPlatformSupport>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::lego::UiPlatformSupport
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        std::string get_time_string() override;
        std::string get_storage_path() override;

    private:
        friend ::djinni::JniInterface<::lego::UiPlatformSupport, ::djinni_generated::NativeUiPlatformSupport>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/lego/UiPlatformSupport") };
    const jmethodID method_getTimeString { ::djinni::jniGetMethodID(clazz.get(), "getTimeString", "()Ljava/lang/String;") };
    const jmethodID method_getStoragePath { ::djinni::jniGetMethodID(clazz.get(), "getStoragePath", "()Ljava/lang/String;") };
};

}  // namespace djinni_generated
