// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "app_manager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAppManager final : ::djinni::JniInterface<::lego::AppManager, NativeAppManager> {
public:
    using CppType = std::shared_ptr<::lego::AppManager>;
    using CppOptType = std::shared_ptr<::lego::AppManager>;
    using JniType = jobject;

    using Boxed = NativeAppManager;

    ~NativeAppManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAppManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAppManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAppManager();
    friend ::djinni::JniClass<NativeAppManager>;
    friend ::djinni::JniInterface<::lego::AppManager, NativeAppManager>;

};

}  // namespace djinni_generated
