// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "djinni_support.hpp"
#include "ui_manager.hpp"

namespace djinni_generated {

class NativeUiManager final : ::djinni::JniInterface<::lego::UiManager, NativeUiManager> {
public:
    using CppType = std::shared_ptr<::lego::UiManager>;
    using CppOptType = std::shared_ptr<::lego::UiManager>;
    using JniType = jobject;

    using Boxed = NativeUiManager;

    ~NativeUiManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeUiManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeUiManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeUiManager();
    friend ::djinni::JniClass<NativeUiManager>;
    friend ::djinni::JniInterface<::lego::UiManager, NativeUiManager>;

};

}  // namespace djinni_generated
