// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class AppManager {
    public abstract void updateTimeString(String timeString);

    public static native AppManager create(AppObserver observer);

    private static final class CppProxy extends AppManager
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void updateTimeString(String timeString)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_updateTimeString(this.nativeRef, timeString);
        }
        private native void native_updateTimeString(long _nativeRef, String timeString);
    }
}
