// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

import java.util.concurrent.atomic.AtomicBoolean;

/** Shared core APIs */
public abstract class LegoCore {
    /** get data, returns template id */
    public abstract String getData();

    /** send data */
    public abstract void sendData(STemplate data);

    /** upload file */
    public abstract void uploadFile(byte[] fileData);

    /** download file */
    public abstract void downloadFile(String fileId);

    /** performance test code */
    public abstract STemplate sendLargeDataOverBridge(String templateId);

    public abstract STemplate generateLargeData(int numberOfPages, int questionsPerPage);

    /** class method to create core API instance */
    public static native LegoCore create(LegoPlatform platform);

    private static final class CppProxy extends LegoCore
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String getData()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getData(this.nativeRef);
        }
        private native String native_getData(long _nativeRef);

        @Override
        public void sendData(STemplate data)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_sendData(this.nativeRef, data);
        }
        private native void native_sendData(long _nativeRef, STemplate data);

        @Override
        public void uploadFile(byte[] fileData)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_uploadFile(this.nativeRef, fileData);
        }
        private native void native_uploadFile(long _nativeRef, byte[] fileData);

        @Override
        public void downloadFile(String fileId)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_downloadFile(this.nativeRef, fileId);
        }
        private native void native_downloadFile(long _nativeRef, String fileId);

        @Override
        public STemplate sendLargeDataOverBridge(String templateId)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_sendLargeDataOverBridge(this.nativeRef, templateId);
        }
        private native STemplate native_sendLargeDataOverBridge(long _nativeRef, String templateId);

        @Override
        public STemplate generateLargeData(int numberOfPages, int questionsPerPage)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_generateLargeData(this.nativeRef, numberOfPages, questionsPerPage);
        }
        private native STemplate native_generateLargeData(long _nativeRef, int numberOfPages, int questionsPerPage);
    }
}
