// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

public final class Question {


    /*package*/ final String mId;

    /*package*/ final String mTitle;

    /*package*/ final int mResponseType;

    /*package*/ final String mDescription;

    /*package*/ final int mOrder;

    public Question(
            String id,
            String title,
            int responseType,
            String description,
            int order) {
        this.mId = id;
        this.mTitle = title;
        this.mResponseType = responseType;
        this.mDescription = description;
        this.mOrder = order;
    }

    /** id of the question */
    public String getId() {
        return mId;
    }

    /** title of the question */
    public String getTitle() {
        return mTitle;
    }

    /** response type */
    public int getResponseType() {
        return mResponseType;
    }

    /** description of the question */
    public String getDescription() {
        return mDescription;
    }

    /** order of the question */
    public int getOrder() {
        return mOrder;
    }

    @Override
    public String toString() {
        return "Question{" +
                "mId=" + mId +
                "," + "mTitle=" + mTitle +
                "," + "mResponseType=" + mResponseType +
                "," + "mDescription=" + mDescription +
                "," + "mOrder=" + mOrder +
        "}";
    }

}
