// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

public final class SQuestion {


    /*package*/ final String mId;

    /*package*/ final String mTitle;

    /*package*/ final int mResponseType;

    /*package*/ final String mQuestionDescription;

    /*package*/ final int mOrder;

    public SQuestion(
            String id,
            String title,
            int responseType,
            String questionDescription,
            int order) {
        this.mId = id;
        this.mTitle = title;
        this.mResponseType = responseType;
        this.mQuestionDescription = questionDescription;
        this.mOrder = order;
    }

    /** id of the question */
    public String getId() {
        return mId;
    }

    /** title of the question */
    public String getTitle() {
        return mTitle;
    }

    /** response type */
    public int getResponseType() {
        return mResponseType;
    }

    /** description of the question */
    public String getQuestionDescription() {
        return mQuestionDescription;
    }

    /** order of the question */
    public int getOrder() {
        return mOrder;
    }

    @Override
    public String toString() {
        return "SQuestion{" +
                "mId=" + mId +
                "," + "mTitle=" + mTitle +
                "," + "mResponseType=" + mResponseType +
                "," + "mQuestionDescription=" + mQuestionDescription +
                "," + "mOrder=" + mOrder +
        "}";
    }

}
