// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

import java.util.ArrayList;

public final class STemplate {


    /*package*/ final String mId;

    /*package*/ final String mName;

    /*package*/ final ArrayList<SPage> mPages;

    public STemplate(
            String id,
            String name,
            ArrayList<SPage> pages) {
        this.mId = id;
        this.mName = name;
        this.mPages = pages;
    }

    /** id of the template */
    public String getId() {
        return mId;
    }

    /** name of the template */
    public String getName() {
        return mName;
    }

    /** pages */
    public ArrayList<SPage> getPages() {
        return mPages;
    }

    @Override
    public String toString() {
        return "STemplate{" +
                "mId=" + mId +
                "," + "mName=" + mName +
                "," + "mPages=" + mPages +
        "}";
    }

}
