// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

public abstract class UiObserver {
    public abstract void titleUpdated(String title);

    public abstract void peopleUpdated(People people);
}
