// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

public abstract class UiPlatformSupport {
    public abstract String getTimeString();

    public abstract String getStoragePath();

    public abstract void getTimeStringAsync(UiManager manager);

    public abstract void postTaskInBackgroundThread(Task task);
}
