// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include <string>

namespace lego {

class AppListener {
public:
    virtual ~AppListener() {}

    virtual void time_string_updated(const std::string & time_string) = 0;
};

}  // namespace lego
