// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lego.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class LegoRecordField;
@class LegoRecordSection;
@class Page;
@class Question;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - LegoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface LegoRoot : GPBRootObject
@end

#pragma mark - GetRequest

typedef GPB_ENUM(GetRequest_FieldNumber) {
  GetRequest_FieldNumber_Flag = 1,
};

@interface GetRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *flag;

@end

#pragma mark - LegoRecordField

typedef GPB_ENUM(LegoRecordField_FieldNumber) {
  LegoRecordField_FieldNumber_Id_p = 1,
  LegoRecordField_FieldNumber_Name = 2,
  LegoRecordField_FieldNumber_Data_p = 3,
};

@interface LegoRecordField : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@end

#pragma mark - LegoRecordSection

typedef GPB_ENUM(LegoRecordSection_FieldNumber) {
  LegoRecordSection_FieldNumber_Id_p = 1,
  LegoRecordSection_FieldNumber_Name = 2,
  LegoRecordSection_FieldNumber_FieldsArray = 3,
};

@interface LegoRecordSection : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LegoRecordField*> *fieldsArray;
/** The number of items in @c fieldsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fieldsArray_Count;

@end

#pragma mark - LegoRecord

typedef GPB_ENUM(LegoRecord_FieldNumber) {
  LegoRecord_FieldNumber_Id_p = 1,
  LegoRecord_FieldNumber_Name = 2,
  LegoRecord_FieldNumber_SectionsArray = 3,
};

@interface LegoRecord : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LegoRecordSection*> *sectionsArray;
/** The number of items in @c sectionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sectionsArray_Count;

@end

#pragma mark - LegoResponse

typedef GPB_ENUM(LegoResponse_FieldNumber) {
  LegoResponse_FieldNumber_Success = 1,
};

@interface LegoResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@end

#pragma mark - Question

typedef GPB_ENUM(Question_FieldNumber) {
  Question_FieldNumber_Id_p = 1,
  Question_FieldNumber_Title = 2,
  Question_FieldNumber_ResponseType = 3,
  Question_FieldNumber_Description_p = 4,
  Question_FieldNumber_Order = 5,
};

@interface Question : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite) int32_t responseType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite) int32_t order;

@end

#pragma mark - Page

typedef GPB_ENUM(Page_FieldNumber) {
  Page_FieldNumber_Id_p = 1,
  Page_FieldNumber_Title = 2,
  Page_FieldNumber_Order = 3,
  Page_FieldNumber_QuestionsArray = 4,
};

@interface Page : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite) int32_t order;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Question*> *questionsArray;
/** The number of items in @c questionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger questionsArray_Count;

@end

#pragma mark - Template

typedef GPB_ENUM(Template_FieldNumber) {
  Template_FieldNumber_Id_p = 1,
  Template_FieldNumber_Name = 2,
  Template_FieldNumber_PagesArray = 3,
};

@interface Template : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Page*> *pagesArray;
/** The number of items in @c pagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pagesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
