// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGAppObserver+Private.h"
#import "LGAppObserver.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class AppObserver::ObjcProxy final
: public ::lego::AppObserver
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::AppObserver;
public:
    using ObjcProxyBase::ObjcProxyBase;
};

}  // namespace djinni_generated

namespace djinni_generated {

auto AppObserver::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto AppObserver::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
