// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import <Foundation/Foundation.h>
@class LGAppManager;
@protocol LGAppObserver;


@interface LGAppManager : NSObject

+ (nullable LGAppManager *)create:(nullable id<LGAppObserver>)observer;

- (void)updateTimeString:(nonnull NSString *)timeString;

@end
