// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "app_manager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGAppManager;

namespace djinni_generated {

class AppManager
{
public:
    using CppType = std::shared_ptr<::lego::AppManager>;
    using CppOptType = std::shared_ptr<::lego::AppManager>;
    using ObjcType = LGAppManager*;

    using Boxed = AppManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

