// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGAppManager+Private.h"
#import "LGAppManager.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "LGAppObserver+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface LGAppManager ()

- (id)initWithCpp:(const std::shared_ptr<::lego::AppManager>&)cppRef;

@end

@implementation LGAppManager {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::lego::AppManager>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::lego::AppManager>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable LGAppManager *)create:(nullable id<LGAppObserver>)observer {
    try {
        auto objcpp_result_ = ::lego::AppManager::create(::djinni_generated::AppObserver::toCpp(observer));
        return ::djinni_generated::AppManager::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)updateTimeString:(nonnull NSString *)timeString {
    try {
        _cppRefHandle.get()->update_time_string(::djinni::String::toCpp(timeString));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto AppManager::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto AppManager::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<LGAppManager>(cpp);
}

}  // namespace djinni_generated

@end
