// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "lego_platform.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol LGLegoPlatform;

namespace djinni_generated {

class LegoPlatform
{
public:
    using CppType = std::shared_ptr<::lego::LegoPlatform>;
    using CppOptType = std::shared_ptr<::lego::LegoPlatform>;
    using ObjcType = id<LGLegoPlatform>;

    using Boxed = LegoPlatform;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

