// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGSTemplate.h"
#import <Foundation/Foundation.h>
@class LGNetworkCallback;


/** Platform APIs */
@protocol LGLegoPlatform

/** get platform specific storage path */
- (nonnull NSString *)getStoragePath;

/**
 * event subscriptions
 * notify UI layer when data is updated
 */
- (void)dataUpdated:(nonnull LGSTemplate *)data;

/** http methods */
- (void)httpDownloadFile:(nonnull NSString *)fileId
                callback:(nullable LGNetworkCallback *)callback;

- (void)httpUploadFile:(nonnull NSString *)path
              callback:(nullable LGNetworkCallback *)callback;

- (void)httpGetData:(nullable LGNetworkCallback *)callback;

- (void)httpSendData:(nonnull LGSTemplate *)data
            callback:(nullable LGNetworkCallback *)callback;

/** grpc methods */
- (void)grpcGetData:(nullable LGNetworkCallback *)callback;

- (void)grpcSendData:(nonnull LGSTemplate *)data
            callback:(nullable LGNetworkCallback *)callback;

@end
