// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "network_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGNetworkCallback;

namespace djinni_generated {

class NetworkCallback
{
public:
    using CppType = std::shared_ptr<::lego::NetworkCallback>;
    using CppOptType = std::shared_ptr<::lego::NetworkCallback>;
    using ObjcType = LGNetworkCallback*;

    using Boxed = NetworkCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

