// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import <Foundation/Foundation.h>


/** Callbacks */
@interface LGNetworkCallback : NSObject

/** http handlers */
- (void)onHttpDownloadFileSuccess:(nonnull NSString *)path;

- (void)onHttpUploadFileSuccess;

@end
