// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGNetworkCallback+Private.h"
#import "LGNetworkCallback.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface LGNetworkCallback ()

- (id)initWithCpp:(const std::shared_ptr<::lego::NetworkCallback>&)cppRef;

@end

@implementation LGNetworkCallback {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::lego::NetworkCallback>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::lego::NetworkCallback>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onHttpDownloadFileSuccess:(nonnull NSString *)path {
    try {
        _cppRefHandle.get()->on_http_download_file_success(::djinni::String::toCpp(path));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)onHttpUploadFileSuccess {
    try {
        _cppRefHandle.get()->on_http_upload_file_success();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto NetworkCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto NetworkCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<LGNetworkCallback>(cpp);
}

}  // namespace djinni_generated

@end
