// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGPage.h"
#include "page.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGPage;

namespace djinni_generated {

struct Page
{
    using CppType = ::lego::Page;
    using ObjcType = LGPage*;

    using Boxed = Page;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
