// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGPeople+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto People::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.firstName),
            ::djinni::String::toCpp(obj.lastName)};
}

auto People::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LGPeople alloc] initWithFirstName:(::djinni::String::fromCpp(cpp.first_name))
                                      lastName:(::djinni::String::fromCpp(cpp.last_name))];
}

}  // namespace djinni_generated
