// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGPeople.h"


@implementation LGPeople

- (nonnull instancetype)initWithFirstName:(nonnull NSString *)firstName
                                 lastName:(nonnull NSString *)lastName
{
    if (self = [super init]) {
        _firstName = [firstName copy];
        _lastName = [lastName copy];
    }
    return self;
}

+ (nonnull instancetype)peopleWithFirstName:(nonnull NSString *)firstName
                                   lastName:(nonnull NSString *)lastName
{
    return [[self alloc] initWithFirstName:firstName
                                  lastName:lastName];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p firstName:%@ lastName:%@>", self.class, (void *)self, self.firstName, self.lastName];
}

@end
