// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import <Foundation/Foundation.h>

/**
 *######################################
 * App Architecture Related Interfaces #
 *######################################
 */
@interface LGPeople : NSObject
- (nonnull instancetype)initWithFirstName:(nonnull NSString *)firstName
                                 lastName:(nonnull NSString *)lastName;
+ (nonnull instancetype)peopleWithFirstName:(nonnull NSString *)firstName
                                   lastName:(nonnull NSString *)lastName;

@property (nonatomic, readonly, nonnull) NSString * firstName;

@property (nonatomic, readonly, nonnull) NSString * lastName;

@end
