// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGQuestion+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Question::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.id),
            ::djinni::String::toCpp(obj.title),
            ::djinni::I32::toCpp(obj.responseType),
            ::djinni::String::toCpp(obj.description),
            ::djinni::I32::toCpp(obj.order)};
}

auto Question::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LGQuestion alloc] initWithId:(::djinni::String::fromCpp(cpp.id))
                                    title:(::djinni::String::fromCpp(cpp.title))
                             responseType:(::djinni::I32::fromCpp(cpp.response_type))
                              description:(::djinni::String::fromCpp(cpp.description))
                                    order:(::djinni::I32::fromCpp(cpp.order))];
}

}  // namespace djinni_generated
