// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGQuestion.h"


@implementation LGQuestion

- (nonnull instancetype)initWithId:(nonnull NSString *)id
                             title:(nonnull NSString *)title
                      responseType:(int32_t)responseType
                       description:(nonnull NSString *)description
                             order:(int32_t)order
{
    if (self = [super init]) {
        _id = [id copy];
        _title = [title copy];
        _responseType = responseType;
        _description = [description copy];
        _order = order;
    }
    return self;
}

+ (nonnull instancetype)questionWithId:(nonnull NSString *)id
                                 title:(nonnull NSString *)title
                          responseType:(int32_t)responseType
                           description:(nonnull NSString *)description
                                 order:(int32_t)order
{
    return [[self alloc] initWithId:id
                              title:title
                       responseType:responseType
                        description:description
                              order:order];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ title:%@ responseType:%@ description:%@ order:%@>", self.class, (void *)self, self.id, self.title, @(self.responseType), self.description, @(self.order)];
}

@end
