// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGQuestion.h"
#include "question.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGQuestion;

namespace djinni_generated {

struct Question
{
    using CppType = ::lego::Question;
    using ObjcType = LGQuestion*;

    using Boxed = Question;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
