// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGSPage.h"


@implementation LGSPage

- (nonnull instancetype)initWithId:(nonnull NSString *)id
                             title:(nonnull NSString *)title
                             order:(int32_t)order
                         questions:(nonnull NSArray<LGSQuestion *> *)questions
{
    if (self = [super init]) {
        _id = [id copy];
        _title = [title copy];
        _order = order;
        _questions = [questions copy];
    }
    return self;
}

+ (nonnull instancetype)sPageWithId:(nonnull NSString *)id
                              title:(nonnull NSString *)title
                              order:(int32_t)order
                          questions:(nonnull NSArray<LGSQuestion *> *)questions
{
    return [[self alloc] initWithId:id
                              title:title
                              order:order
                          questions:questions];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ title:%@ order:%@ questions:%@>", self.class, (void *)self, self.id, self.title, @(self.order), self.questions];
}

@end
