// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGSPage+Private.h"
#import "DJIMarshal+Private.h"
#import "LGSQuestion+Private.h"
#include <cassert>

namespace djinni_generated {

auto SPage::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.id),
            ::djinni::String::toCpp(obj.title),
            ::djinni::I32::toCpp(obj.order),
            ::djinni::List<::djinni_generated::SQuestion>::toCpp(obj.questions)};
}

auto SPage::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LGSPage alloc] initWithId:(::djinni::String::fromCpp(cpp.id))
                                 title:(::djinni::String::fromCpp(cpp.title))
                                 order:(::djinni::I32::fromCpp(cpp.order))
                             questions:(::djinni::List<::djinni_generated::SQuestion>::fromCpp(cpp.questions))];
}

}  // namespace djinni_generated
