// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGSPage.h"
#include "s_page.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGSPage;

namespace djinni_generated {

struct SPage
{
    using CppType = ::lego::SPage;
    using ObjcType = LGSPage*;

    using Boxed = SPage;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
