// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGSQuestion.h"
#include "s_question.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGSQuestion;

namespace djinni_generated {

struct SQuestion
{
    using CppType = ::lego::SQuestion;
    using ObjcType = LGSQuestion*;

    using Boxed = SQuestion;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
