// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGSTemplate.h"
#include "s_template.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGSTemplate;

namespace djinni_generated {

struct STemplate
{
    using CppType = ::lego::STemplate;
    using ObjcType = LGSTemplate*;

    using Boxed = STemplate;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
