// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGSTemplate.h"


@implementation LGSTemplate

- (nonnull instancetype)initWithId:(nonnull NSString *)id
                              name:(nonnull NSString *)name
                             pages:(nonnull NSArray<LGSPage *> *)pages
{
    if (self = [super init]) {
        _id = [id copy];
        _name = [name copy];
        _pages = [pages copy];
    }
    return self;
}

+ (nonnull instancetype)sTemplateWithId:(nonnull NSString *)id
                                   name:(nonnull NSString *)name
                                  pages:(nonnull NSArray<LGSPage *> *)pages
{
    return [[self alloc] initWithId:id
                               name:name
                              pages:pages];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ name:%@ pages:%@>", self.class, (void *)self, self.id, self.name, self.pages];
}

@end
