// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import <Foundation/Foundation.h>


/**
 *######################################
 * App Architecture Related Interfaces #
 *######################################
 */
@interface LGTask : NSObject

- (void)execute;

@end
