// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGTask+Private.h"
#import "LGTask.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface LGTask ()

- (id)initWithCpp:(const std::shared_ptr<::lego::Task>&)cppRef;

@end

@implementation LGTask {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::lego::Task>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::lego::Task>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)execute {
    try {
        _cppRefHandle.get()->execute();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Task::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Task::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<LGTask>(cpp);
}

}  // namespace djinni_generated

@end
