// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGPage.h"
#import <Foundation/Foundation.h>

@interface LGTemplate : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                              name:(nonnull NSString *)name
                             pages:(nonnull NSArray<LGPage *> *)pages;
+ (nonnull instancetype)templateWithId:(nonnull NSString *)id
                                  name:(nonnull NSString *)name
                                 pages:(nonnull NSArray<LGPage *> *)pages;

/** id of the template */
@property (nonatomic, readonly, nonnull) NSString * id;

/** name of the template */
@property (nonatomic, readonly, nonnull) NSString * name;

/** pages */
@property (nonatomic, readonly, nonnull) NSArray<LGPage *> * pages;

@end
