// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGTemplate.h"
#include "template.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGTemplate;

namespace djinni_generated {

struct Template
{
    using CppType = ::lego::Template;
    using ObjcType = LGTemplate*;

    using Boxed = Template;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
