// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGTemplate+Private.h"
#import "DJIMarshal+Private.h"
#import "LGPage+Private.h"
#include <cassert>

namespace djinni_generated {

auto Template::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.id),
            ::djinni::String::toCpp(obj.name),
            ::djinni::List<::djinni_generated::Page>::toCpp(obj.pages)};
}

auto Template::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LGTemplate alloc] initWithId:(::djinni::String::fromCpp(cpp.id))
                                     name:(::djinni::String::fromCpp(cpp.name))
                                    pages:(::djinni::List<::djinni_generated::Page>::fromCpp(cpp.pages))];
}

}  // namespace djinni_generated
