// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "ui_manager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGUiManager;

namespace djinni_generated {

class UiManager
{
public:
    using CppType = std::shared_ptr<::lego::UiManager>;
    using CppOptType = std::shared_ptr<::lego::UiManager>;
    using ObjcType = LGUiManager*;

    using Boxed = UiManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

