// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import <Foundation/Foundation.h>
@class LGTask;
@class LGUiManager;


@protocol LGUiPlatformSupport

- (nonnull NSString *)getTimeString;

- (nonnull NSString *)getStoragePath;

- (void)getTimeStringAsync:(nullable LGUiManager *)manager;

- (void)postTaskInBackgroundThread:(nullable LGTask *)task;

@end
