// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import <Foundation/Foundation.h>


@protocol LGUiPlatformSupport

- (nonnull NSString *)getTimeString;

@end
