// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGUiObserver+Private.h"
#import "LGUiObserver.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "LGPeople+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class UiObserver::ObjcProxy final
: public ::lego::UiObserver
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::UiObserver;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void title_updated(const std::string & c_title) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() titleUpdated:(::djinni::String::fromCpp(c_title))];
        }
    }
    void people_updated(const ::lego::People & c_people) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() peopleUpdated:(::djinni_generated::People::fromCpp(c_people))];
        }
    }
    void time_string_updated(const std::string & c_time_string) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() timeStringUpdated:(::djinni::String::fromCpp(c_time_string))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto UiObserver::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto UiObserver::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
