// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#import "LGPeople.h"
#import <Foundation/Foundation.h>


@protocol LGUiObserver

- (void)titleUpdated:(nonnull NSString *)title;

- (void)peopleUpdated:(nonnull LGPeople *)people;

- (void)timeStringUpdated:(nonnull NSString *)timeString;

@end
