// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#include "ui_observer.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol LGUiObserver;

namespace djinni_generated {

class UiObserver
{
public:
    using CppType = std::shared_ptr<::lego::UiObserver>;
    using CppOptType = std::shared_ptr<::lego::UiObserver>;
    using ObjcType = id<LGUiObserver>;

    using Boxed = UiObserver;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

