// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

namespace lego {

class AppObserver {
public:
    virtual ~AppObserver() {}
};

}  // namespace lego
