// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include <memory>
#include <string>

namespace lego {

class AppObserver;

class AppManager {
public:
    virtual ~AppManager() {}

    static std::shared_ptr<AppManager> create(const std::shared_ptr<AppObserver> & observer);

    virtual void update_time_string(const std::string & time_string) = 0;
};

}  // namespace lego
