// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include <memory>
#include <string>

namespace lego {

class NetworkCallback;
struct STemplate;

/** Platform APIs */
class LegoPlatform {
public:
    virtual ~LegoPlatform() {}

    /** get platform specific storage path */
    virtual std::string get_storage_path() = 0;

    /**
     * event subscriptions
     * notify UI layer when data is updated
     */
    virtual void data_updated(const STemplate & data) = 0;

    /** http methods */
    virtual void http_download_file(const std::string & file_id, const std::shared_ptr<NetworkCallback> & callback) = 0;

    virtual void http_upload_file(const std::string & path, const std::shared_ptr<NetworkCallback> & callback) = 0;
};

}  // namespace lego
