// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include <string>

namespace lego {

struct Template;

/** Callbacks */
class NetworkCallback {
public:
    virtual ~NetworkCallback() {}

    /** http handlers */
    virtual void on_http_download_file_success(const std::string & path) = 0;

    virtual void on_http_upload_file_success() = 0;

    virtual void on_http_get_data_success(const std::string & path) = 0;

    virtual void on_http_send_data_success() = 0;

    /** grpc handlers */
    virtual void on_grpc_get_data_success(const Template & data) = 0;

    virtual void on_grpc_send_data_success() = 0;
};

}  // namespace lego
