// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "question.hpp"
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace lego {

struct Page final {
    /** id of the page */
    std::string id;
    /** title of the page */
    std::string title;
    /** order of the page */
    int32_t order;
    /** questions */
    std::vector<Question> questions;

    Page(std::string id_,
         std::string title_,
         int32_t order_,
         std::vector<Question> questions_)
    : id(std::move(id_))
    , title(std::move(title_))
    , order(std::move(order_))
    , questions(std::move(questions_))
    {}
};

}  // namespace lego
