// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include <string>
#include <utility>

namespace lego {

/**
 *######################################
 * App Architecture Related Interfaces #
 *######################################
 */
struct People final {
    std::string first_name;
    std::string last_name;

    People(std::string first_name_,
           std::string last_name_)
    : first_name(std::move(first_name_))
    , last_name(std::move(last_name_))
    {}
};

}  // namespace lego
