// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

namespace lego {

/**
 *######################################
 * App Architecture Related Interfaces #
 *######################################
 */
class Task {
public:
    virtual ~Task() {}

    virtual void execute() = 0;
};

}  // namespace lego
