// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include "page.hpp"
#include <string>
#include <utility>
#include <vector>

namespace lego {

struct Template final {
    /** id of the template */
    std::string id;
    /** name of the template */
    std::string name;
    /** pages */
    std::vector<Page> pages;

    Template(std::string id_,
             std::string name_,
             std::vector<Page> pages_)
    : id(std::move(id_))
    , name(std::move(name_))
    , pages(std::move(pages_))
    {}
};

}  // namespace lego
