// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include <string>

namespace lego {

struct People;

class UiObserver {
public:
    virtual ~UiObserver() {}

    virtual void title_updated(const std::string & title) = 0;

    virtual void people_updated(const People & people) = 0;
};

}  // namespace lego
