// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include <string>

namespace lego {

class UiPlatformSupport {
public:
    virtual ~UiPlatformSupport() {}

    virtual std::string get_time_string() = 0;
};

}  // namespace lego
