// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

#pragma once

#include <memory>
#include <string>

namespace lego {

class Task;
class UiManager;

class UiPlatformSupport {
public:
    virtual ~UiPlatformSupport() {}

    virtual std::string get_time_string() = 0;

    virtual std::string get_storage_path() = 0;

    virtual void get_time_string_async(const std::shared_ptr<UiManager> & manager) = 0;

    virtual void post_task_in_background_thread(const std::shared_ptr<Task> & task) = 0;

    virtual void post_task_in_main_thread(const std::shared_ptr<Task> & task) = 0;
};

}  // namespace lego
