// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

/** Platform APIs */
public abstract class LegoPlatform {
    /** get platform specific storage path */
    public abstract String getStoragePath();

    /**
     * event subscriptions
     * notify UI layer when data is updated
     */
    public abstract void dataUpdated(STemplate data);

    /** http methods */
    public abstract void httpDownloadFile(String fileId, NetworkCallback callback);

    public abstract void httpUploadFile(String path, NetworkCallback callback);
}
