// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lego.djinni

package com.mycompany.lego;

import java.util.ArrayList;

public final class SPage {


    /*package*/ final String mId;

    /*package*/ final String mTitle;

    /*package*/ final int mOrder;

    /*package*/ final ArrayList<SQuestion> mQuestions;

    public SPage(
            String id,
            String title,
            int order,
            ArrayList<SQuestion> questions) {
        this.mId = id;
        this.mTitle = title;
        this.mOrder = order;
        this.mQuestions = questions;
    }

    /** id of the page */
    public String getId() {
        return mId;
    }

    /** title of the page */
    public String getTitle() {
        return mTitle;
    }

    /** order of the page */
    public int getOrder() {
        return mOrder;
    }

    /** questions */
    public ArrayList<SQuestion> getQuestions() {
        return mQuestions;
    }

    @Override
    public String toString() {
        return "SPage{" +
                "mId=" + mId +
                "," + "mTitle=" + mTitle +
                "," + "mOrder=" + mOrder +
                "," + "mQuestions=" + mQuestions +
        "}";
    }

}
